In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text

# 数据库配置
username = "XXXXXX"
password = "YYYYYY"
host = "localhost"
port = 5432
database = "eyewear-data"

# 创建连接
engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# 查询数据
sql = """
SELECT *
FROM "Order";
"""

df = pd.read_sql(sql, engine)

# 查看数据
df

,order_id,customer_id,order_m3_code,order_date,approval_date,delivery_date,order_status,shipping_fee,tax_amount,total_price_before_discount_and_tax,total_price_before_tax,total_price_after_tax,is_shipping_free,is_reward_points,is_insurance,store_id,campaign_id
0,1832,24716,RBORD20231001832,2023-02-06 20:43:43,2023-02-07 20:43:43,2023-02-10 20:43:43,Completed,0.0,113.74,1197.30,1197.30,1311.04,True,True,False,90,NaN
1,1833,106869,RBORD20231001833,2023-03-13 08:07:51,2023-03-13 08:07:51,2023-03-22 08:07:51,Cancelled,0.0,24.83,261.32,261.32,286.15,True,False,False,6,NaN
2,1834,32177,RBORD20231001834,2023-02-28 15:53:30,2023-03-01 15:53:30,2023-03-07 15:53:30,Completed,0.0,17.16,180.65,180.65,197.81,True,False,False,38,NaN
3,1835,88952,RBORD20231001835,2023-03-17 18:25:35,2023-03-18 18:25:35,2023-03-21 18:25:35,Completed,20.0,16.28,171.37,191.37,207.65,False,True,False,43,NaN
4,1836,9681,RBORD20231001836,2023-01-08 01:27:25,2023-01-08 01:27:25,2023-01-17 01:27:25,Completed,0.0,49.35,519.45,519.45,568.80,True,True,False,89,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,1827,108107,RBORD20231001827,2023-03-23 02:39:02,2023-03-24 02:39:02,2023-03-27 02:39:02,Cancelled,0.0,22.56,237.44,237.44,260.00,True,False,False,39,NaN
499996,1828,94907,RBORD20231001828,2023-02-15 09:49:34,2023-02-15 09:49:34,2023-02-19 09:49:34,Shipped,0.0,19.61,251.76,206.44,226.05,True,False,False,18,3.0
499997,1829,31190,RBORD20231001829,2023-01-11 02:01:43,2023-01-12 02:01:43,2023-01-17 02:01:43,Completed,0.0,23.62,248.66,248.66,272.28,True,False,False,58,NaN
499998,1830,103662,RBORD20231001830,2023-02-02 06:15:07,2023-02-03 06:15:07,2023-02-12 06:15:07,Cancelled,0.0,50.58,532.39,532.39,582.97,True,True,False,93,NaN
499999,1831,156228,RBORD20231001831,2023-02-11 10:27:32,2023-02-12 10:27:32,2023-02-20 10:27:32,Completed,0.0,17.16,180.65,180.65,197.81,True,False,False,17,NaN

In [6]:
df['order_status'].unique()

array(['Completed', 'Cancelled', 'Shipped', 'Pending'], dtype=object)

In [8]:
sql_2 = """
SELECT order_status, COUNT(*) AS cnt
FROM "Order"
GROUP BY order_status
ORDER BY cnt DESC;
"""
df_2 = pd.read_sql(sql_2, engine)

# 查看聚合结果
df_2.to_parquet("2023_2024_order_status_aggregate.parquet",engine = 'fastparquet',index=False)
print("聚合结果已保存为 2023_2024_order_status_aggregate.parquet")
df_2

聚合结果已保存为 2023_2024_order_status_aggregate.parquet

  order_status     cnt
0    Completed  353013
1      Shipped   91290
2      Pending   41302
3    Cancelled   14395