### 读取数据

In [9]:
import pandas as pd
dir = r"customer_reviews_non_english.csv"
df = pd.read_csv(dir)
df

,review_id,customer_id,product_id,order_id,rating,review_title,review_text,review_date,text,text_clean,lang,text_clean_translated
0,16,150759,35,200649,5,Excelentes a mi esposo le encantan,Excelentes a mi esposo le encantan Service wa...,2024-11-24,Excelentes a mi esposo le encantan Excelentes...,excelentes a mi esposo le encantan excelentes ...,es,NaN
1,41,82151,10,243155,5,Excelentes a mi esposo le encantan,Excelentes a mi esposo le encantan,2024-07-27,Excelentes a mi esposo le encantan Excelentes...,excelentes a mi esposo le encantan excelentes ...,es,NaN
2,332,64201,184,1530,5,Excellent,Excellent product and seller.,2024-10-10,Excellent Excellent product and seller.,excellent excellent product and seller.,fr,NaN
3,249,18714,72,274097,5,Buena calidad,Muy buen tamaño y calidad,2023-12-03,Buena calidad Muy buen tamaño y calidad,buena calidad muy buen tamaño y calidad,es,NaN
4,281,83376,96,45097,5,Five Stars,Excellent,2024-02-20,Five Stars Excellent,five stars excellent,fr,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
752,49430,63622,37,404169,5,Excelentes a mi esposo le encantan,Excelentes a mi esposo le encantan,2025-03-30,Excelentes a mi esposo le encantan Excelentes...,excelentes a mi esposo le encantan excelentes ...,es,NaN
753,49581,93070,181,264986,5,Lentes,Muy buenas gafas de sol muchas gracias. Hope t...,2024-04-18,Lentes Muy buenas gafas de sol muchas gracias....,lentes muy buenas gafas de sol muchas gracias....,es,NaN
754,49626,26395,169,218440,2,very wide,"Too wide, don't darken much",2024-05-04,"very wide Too wide, don't darken much","very wide too wide, don't darken much",nl,NaN
755,49867,66741,81,217885,5,Como se esperaba,Excelente,2023-12-28,Como se esperaba Excelente,como se esperaba excelente,es,NaN
756,49990,969,126,149812,5,LOVE,super cute and seem durable,2024-06-20,LOVE super cute and seem durable,love super cute and seem durable,fr,NaN

### 去掉text前后的空格，并且去重，并且导出

In [10]:
# 复制数据，避免修改原 df
df_cleaned = df.copy()

# 去除每行前后空格（.str.strip() 会保留 NaN）
df_cleaned['text_clean'] = df_cleaned['text_clean'].str.strip()

# 删除空值、按 text_clean 去重并重置索引
df_cleaned = (
    df_cleaned
    .dropna(subset=['text_clean'])
    .drop_duplicates(subset=['text_clean'])
    .reset_index(drop=True)
)

df_cleaned.to_csv("customer_reviews_non_english_cleaned.csv", index=False, encoding="utf-8-sig")

In [11]:
df_cleaned

,review_id,customer_id,product_id,order_id,rating,review_title,review_text,review_date,text,text_clean,lang,text_clean_translated
0,16,150759,35,200649,5,Excelentes a mi esposo le encantan,Excelentes a mi esposo le encantan Service wa...,2024-11-24,Excelentes a mi esposo le encantan Excelentes...,excelentes a mi esposo le encantan excelentes ...,es,NaN
1,41,82151,10,243155,5,Excelentes a mi esposo le encantan,Excelentes a mi esposo le encantan,2024-07-27,Excelentes a mi esposo le encantan Excelentes...,excelentes a mi esposo le encantan excelentes ...,es,NaN
2,332,64201,184,1530,5,Excellent,Excellent product and seller.,2024-10-10,Excellent Excellent product and seller.,excellent excellent product and seller.,fr,NaN
3,249,18714,72,274097,5,Buena calidad,Muy buen tamaño y calidad,2023-12-03,Buena calidad Muy buen tamaño y calidad,buena calidad muy buen tamaño y calidad,es,NaN
4,281,83376,96,45097,5,Five Stars,Excellent,2024-02-20,Five Stars Excellent,five stars excellent,fr,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
338,48579,64356,81,96575,5,Muy bien como lo esperaba,Para un regalo y quedó perfecto Would buy from...,2023-10-15,Muy bien como lo esperaba Para un regalo y que...,muy bien como lo esperaba para un regalo y que...,es,NaN
339,48944,84863,179,322125,1,No recibí el producto solicitado,Me remitieron las gafas erradas,2025-01-26,No recibí el producto solicitado Me remitieron...,no recibí el producto solicitado me remitieron...,es,NaN
340,48966,89431,149,212686,5,Puntualidad y excelente calidad,Puntualidad y excelente calidad Service was fr...,2025-05-05,Puntualidad y excelente calidad Puntualidad y ...,puntualidad y excelente calidad puntualidad y ...,es,NaN
341,49581,93070,181,264986,5,Lentes,Muy buenas gafas de sol muchas gracias. Hope t...,2024-04-18,Lentes Muy buenas gafas de sol muchas gracias....,lentes muy buenas gafas de sol muchas gracias....,es,NaN
342,49626,26395,169,218440,2,very wide,"Too wide, don't darken much",2024-05-04,"very wide Too wide, don't darken much","very wide too wide, don't darken much",nl,NaN

### 翻译工作在google sheet完成了。

### 转换格式

In [ ]:
dir_translated = r"customer_reviews_non_english_translated - 工作表1.csv"
df_translated = pd.read_csv(dir_translated)

df_translated.to_csv("customer_reviews_non_english_translated.csv", index=False, encoding="utf-8-sig")

In [12]:
df_translated

,review_id,customer_id,product_id,order_id,rating,review_title,review_text,review_date,text,text_clean,lang,text_clean_translated
0,16,150759,35,200649,5,Excelentes a mi esposo le encantan,Excelentes a mi esposo le encantan Service was...,2024/11/24,Excelentes a mi esposo le encantan Excelentes ...,excelentes a mi esposo le encantan excelentes ...,es,"Excellent, my husband loves them. Excellent, m..."
1,41,82151,10,243155,5,Excelentes a mi esposo le encantan,Excelentes a mi esposo le encantan,2024/7/27,Excelentes a mi esposo le encantan Excelentes ...,excelentes a mi esposo le encantan excelentes ...,es,"Excellent, my husband loves them!"
2,332,64201,184,1530,5,Excellent,Excellent product and seller.,2024/10/10,Excellent Excellent product and seller.,excellent excellent product and seller.,fr,excellent excellent product and seller.
3,249,18714,72,274097,5,Buena calidad,Muy buen tamaño y calidad,2023/12/3,Buena calidad Muy buen tamaño y calidad,buena calidad muy buen tamaño y calidad,es,"Good quality, very good size and quality"
4,281,83376,96,45097,5,Five Stars,Excellent,2024/2/20,Five Stars Excellent,five stars excellent,fr,five stars excellent
...,...,...,...,...,...,...,...,...,...,...,...,...
346,48944,84863,179,322125,1,No recibí el producto solicitado,Me remitieron las gafas erradas,2025/1/26,No recibí el producto solicitado Me remitieron...,no recibí el producto solicitado me remitieron...,es,I did not receive the product I ordered; they ...
347,48966,89431,149,212686,5,Puntualidad y excelente calidad,Puntualidad y excelente calidad Service was fr...,2025/5/5,Puntualidad y excelente calidad Puntualidad y ...,puntualidad y excelente calidad puntualidad y ...,es,Punctuality and excellent quality. The service...
348,49506,47863,128,331099,5,Super cute,Rounded out her entire costume.,2024/12/19,Super cute Rounded out her entire costume.,super cute rounded out her entire costume.,fr,super cute rounded out her entire costume.
349,49581,93070,181,264986,5,Lentes,Muy buenas gafas de sol muchas gracias. Hope t...,2024/4/18,Lentes Muy buenas gafas de sol muchas gracias....,lentes muy buenas gafas de sol muchas gracias....,es,"Very good sunglasses, thank you very much. Hop..."
350,49626,26395,169,218440,2,very wide,"Too wide, don't darken much",2024/5/4,"very wide Too wide, don't darken much","very wide too wide, don't darken much",nl,"very wide too wide, don't darken much"