### Connect postgresql database

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# 数据库配置
username = "XXXXXX"
password = "YYYYYY"
host = "localhost"
port = 5432
database = "eyewear-data"

# 创建连接
engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# 查询数据
sql = """
SELECT *
FROM "OrderItem";
"""

df = pd.read_sql(sql, engine)

# 查看数据
df

,order_item_id,order_id,product_id,product_m3_code,product_name,quantity,unit,unit_price,line_price_before_tax,line_price_after_tax,discount_rate,is_free_gift
0,1,1,200,RB-LS-0040,Ray-Ban Mirror Single vision,1,pair,289.28,231.42,253.40,0.80,False
1,2,1,79,RB-FR-0079,Ray-Ban Kai Non-prescription,1,pair,187.38,149.90,164.14,0.80,False
2,3,2,120,RB-FR-0120,Ray-Ban Aviator Classic Prescription,1,pair,176.95,145.10,158.88,0.82,False
3,4,3,136,RB-FR-0136,Ray-Ban Original Wayfarer Prescription,1,pair,161.62,161.62,176.97,1.00,False
4,5,3,197,RB-LS-0037,Ray-Ban Transitions Single vision,1,pair,282.90,282.90,309.78,1.00,False
...,...,...,...,...,...,...,...,...,...,...,...,...
738176,738177,499997,28,RB-FR-0028,Ray-Ban Kai Prescription,2,pair,225.66,451.32,494.20,1.00,False
738177,738178,499998,100,RB-FR-0100,Ray-Ban Ray-Ban Reverse Prescription,1,pair,295.09,191.81,210.03,0.65,False
738178,738179,499999,134,RB-FR-0134,Ray-Ban Ray-Ban Reverse Prescription,1,pair,321.38,321.38,351.91,1.00,False
738179,738180,499999,82,RB-FR-0082,Ray-Ban Ray-Ban Meta Non-prescription,3,pair,217.07,651.21,713.07,1.00,False
738180,738181,500000,155,RB-FR-0155,Ray-Ban New Wayfarer Non-prescription,1,pair,184.55,184.55,202.08,1.00,False

In [2]:
df.columns

Index(['order_item_id', 'order_id', 'product_id', 'product_m3_code',
       'product_name', 'quantity', 'unit', 'unit_price',
       'line_price_before_tax', 'line_price_after_tax', 'discount_rate',
       'is_free_gift'],
      dtype='object')

In [ ]:
import numpy as np
df[(df['quantity'] == 3) & (np.isclose(df['unit_price'], df['line_price_before_tax'] * 3, atol=0.01))]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, product_m3_code, product_name, quantity, unit, unit_price, line_price_before_tax, line_price_after_tax, discount_rate, is_free_gift]
Index: []